version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/node_modules
    environment:
     - VITE_FIREBASE_API_KEY=your_firebase_api_key
     - VITE_FIREBASE_AUTH_DOMAIN=your_auth_domain
     - VITE_FIREBASE_PROJECT_ID=your_project_id
     - VITE_FIREBASE_STORAGE_BUCKET=your_storage_bucket
     - VITE_FIREBASE_MESSAGING_SENDER_ID=your_messaging_sender_id
     - VITE_FIREBASE_APP_ID=your_app_id
     - VITE_FIREBASE_MEASUREMENT_ID=your_measurement_id

  backend:
    build:
      context: ./backend
    ports:
      - "4001:4001"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://postgres.vupfzwmvbozdsokdrkfw:[YOUR-PASSWORD]@aws-0-ap-south-1.pooler.supabase.com:6543/postgres
      - NODE_ENV=development
